<?php

namespace Tests\Data;

use App\Models\External\TicketModel;
use App\Repositories\Mappers\PestRoutesTicketToExternalModelMapper;
use Aptive\PestRoutesSDK\Resources\Tickets\Ticket;

/**
 * @extends AbstractTestPestRoutesData<Ticket, TicketModel>
 */
class TicketData extends AbstractTestPestRoutesData
{
    protected static function getSignature(): array
    {
        return [
            'ticketID' => random_int(10000, 99999),
            'customerID' => 2550260,
            'appointmentID' => 25560,
            'invoiceNumber' => 'WUBB1234567',
            'dateCreated' => '2022-07-29T16:00:00.000000+0000',
            'invoiceDate' => '2022-07-29T16:00:00.000000+0000',
            'dateUpdated' => '2022-07-29T16:00:00.000000+0000',
            'subTotal' => 30.00,
            'taxAmount' => 5.95,
            'total' => 35.95,
            'balance' => 15.95,
            'billToAccountID' => 2550260,
            'officeID' => 1,
            'serviceCharge' => 0,
            'productionValue' => 0,
            'taxRate' => 5.0,
            'renewalID' => null,
            'autoGenerated' => null,
            'serviceID' => 0,
            'items' => [],
            'glNumber' => '',
            'subscriptionID' => 0,
            'serviceTaxable' => '0',
            'active' => 1,
            'autoGeneratedType' => 'INITIAL',
            'templateType' => 'NA',
        ];
    }

    protected static function getRequiredEntityClass(): string
    {
        return Ticket::class;
    }

    protected static function getMapperClass(): string
    {
        return PestRoutesTicketToExternalModelMapper::class;
    }
}
